import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val hilt_navigation_fragment: String = "androidx.hilt:hilt-navigation-fragment:_"

    public const val hilt_work: String = "androidx.hilt:hilt-work:_"

    public const val lifecycle_common: String = "androidx.lifecycle:lifecycle-common:_"

    public const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:_"

    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val paging_common_ktx: String = "androidx.paging:paging-common-ktx:_"

    public const val paging_runtime_ktx: String = "androidx.paging:paging-runtime-ktx:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx:_"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val com_github_bumptech_glide_compiler: String =
            "com.github.bumptech.glide:compiler:_"

    public const val glide: String = "com.github.bumptech.glide:glide:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val gson: String = "com.google.code.gson:gson:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_compiler: String = "com.google.dagger:hilt-compiler:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jetbrains_kotlin_android_gradle_plugin: String =
            "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val spring_web: String = "org.springframework:spring-web:_"
}
